name: 'Build ATP'
description: 'Compile atpd binary'
inputs:
  version:
    required: true
  cc-path:
    required: true
  strip-path:
    required: true
  libev-include-path:
    required: true
  libev-lib-path:
    required: true

runs:
  using: "composite"
  steps:
    - name: Run Make
      shell: bash
      run: |
        make CC=${{ inputs.cc-path }} \
             STRIP=${{ inputs.strip-path }} \
             VERSION=${{ inputs.version }} \
             LIBEV_INC=${{ inputs.libev-include-path }} \
             LIBEV_LIB=${{ inputs.libev-lib-path }}

