#!/bin/bash
# Auto-generate version.h from Git tags or fallback

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
VERSION_FILE="${PROJECT_ROOT}/include/version.h"

# Default version (fallback)
DEFAULT_VERSION="0.0.1"
DEFAULT_BRANCH="unknown"
DEFAULT_COMMIT="0000000"

# Try to get Git information
if command -v git >/dev/null 2>&1 && [ -d "${PROJECT_ROOT}/.git" ]; then
    cd "$PROJECT_ROOT"
    
    GIT_DESCRIBE=$(git describe --tags --dirty=-dirty 2>/dev/null)
    
    if [ -n "$GIT_DESCRIBE" ]; then
        VERSION=$(echo "$GIT_DESCRIBE" | sed 's/^v//' | sed 's/-g[0-9a-f]*//' | sed 's/-[0-9]*$//')
        BUILD_NUM=$(echo "$GIT_DESCRIBE" | grep -oP '-\d+-g' | sed 's/-//g' | sed 's/g//' | head -1)
        if [ -z "$BUILD_NUM" ]; then
            BUILD_NUM="0"
        fi
        if echo "$GIT_DESCRIBE" | grep -q "dirty"; then
            DIRTY="-dirty"
        else
            DIRTY=""
        fi
    else
        VERSION="$DEFAULT_VERSION"
        BUILD_NUM="0"
        DIRTY=""
    fi
    
    BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "$DEFAULT_BRANCH")
    COMMIT=$(git rev-parse --short=7 HEAD 2>/dev/null || echo "$DEFAULT_COMMIT")
    
    if git diff --quiet && git diff --cached --quiet; then
        CLEAN="1"
    else
        CLEAN="0"
    fi
else
    VERSION="$DEFAULT_VERSION"
    BUILD_NUM="0"
    BRANCH="$DEFAULT_BRANCH"
    COMMIT="$DEFAULT_COMMIT"
    DIRTY=""
    CLEAN="0"
fi

# Generate version.h
cat > "$VERSION_FILE" << EOF
/* Auto-generated by gen_version.sh - DO NOT EDIT */

#ifndef ATP_VERSION_H
#define ATP_VERSION_H

#define ATP_VERSION_STRING    "${VERSION}${DIRTY}"
#define ATP_VERSION_MAJOR     $(echo "$VERSION" | cut -d. -f1 2>/dev/null || echo "0")
#define ATP_VERSION_MINOR     $(echo "$VERSION" | cut -d. -f2 2>/dev/null || echo "0")
#define ATP_VERSION_PATCH     $(echo "$VERSION" | cut -d. -f3 | cut -d- -f1 2>/dev/null || echo "0")
#define ATP_VERSION_SUFFIX    "$(echo "$VERSION" | cut -d- -f2- 2>/dev/null)"
#define ATP_VERSION_BUILD     ${BUILD_NUM:-0}
#define ATP_VERSION_COMMIT    "${COMMIT}"
#define ATP_VERSION_BRANCH    "${BRANCH}"
#define ATP_VERSION_DIRTY     "${DIRTY}"
#define ATP_VERSION_CLEAN     ${CLEAN}

#define ATP_BUILD_DATE        __DATE__
#define ATP_BUILD_TIME        __TIME__
#define ATP_BUILD_COMPILER    "aarch64-linux-musl-gcc"
#define ATP_BUILD_ARCH        "ARM64"

/* Function declarations */
const char* atp_get_version(void);
const char* atp_get_full_version(void);
int atp_get_version_major(void);
int atp_get_version_minor(void);
int atp_get_version_patch(void);
const char* atp_get_version_suffix(void);
int atp_get_version_build(void);
const char* atp_get_version_commit(void);
const char* atp_get_version_branch(void);
int atp_is_dirty(void);
int atp_is_clean(void);
const char* atp_get_build_date(void);
const char* atp_get_build_time(void);
const char* atp_get_compiler(void);
const char* atp_get_arch(void);

#endif /* ATP_VERSION_H */
EOF

echo "Generated ${VERSION_FILE}: ATP_VERSION_STRING=\"${VERSION}${DIRTY}\""
