#!/bin/bash
set -e

TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
SHORT_HASH=$(git rev-parse --short=8 HEAD 2>/dev/null || echo "unknown")

if [ -z "$TAG" ]; then
    VERSION="0.0.0-0-g${SHORT_HASH}"
else
    SEMANTIC_VERSION="${TAG#v}"
    COMMIT_SINCE_TAG=$(git rev-list --count "$TAG"..HEAD 2>/dev/null || echo "0")

    if [ "$COMMIT_SINCE_TAG" -eq 0 ]; then
        VERSION="${SEMANTIC_VERSION}"
    else
        VERSION="${SEMANTIC_VERSION}-${COMMIT_SINCE_TAG}-g${SHORT_HASH}"
    fi
fi

cat > include/version.h << EOF2
/* Generated by scripts/gen_version.sh. */
#ifndef ATP_VERSION_H
#define ATP_VERSION_H

#define ATP_VERSION_STRING  "${VERSION}"
#define ATP_VERSION         "${VERSION}"
#define ATP_COMMIT          "${SHORT_HASH}"

#endif /* ATP_VERSION_H */
EOF2

echo "Generated version: ${VERSION}"
