/* Auto-generated by gen_version.sh - DO NOT EDIT */

#ifndef ATP_VERSION_H
#define ATP_VERSION_H

#define ATP_VERSION_STRING    "0.0.1"
#define ATP_VERSION_MAJOR     0
#define ATP_VERSION_MINOR     0
#define ATP_VERSION_PATCH     1
#define ATP_VERSION_SUFFIX    ""
#define ATP_VERSION_BUILD     0
#define ATP_VERSION_COMMIT    "0000000"
#define ATP_VERSION_BRANCH    "unknown"
#define ATP_VERSION_DIRTY     ""
#define ATP_VERSION_CLEAN     1

#define ATP_BUILD_DATE        __DATE__
#define ATP_BUILD_TIME        __TIME__
#define ATP_BUILD_COMPILER    "aarch64-linux-musl-gcc"
#define ATP_BUILD_ARCH        "ARM64"

/* Function declarations */
const char* atp_get_version(void);
const char* atp_get_full_version(void);
int atp_get_version_major(void);
int atp_get_version_minor(void);
int atp_get_version_patch(void);
const char* atp_get_version_suffix(void);
int atp_get_version_build(void);
const char* atp_get_version_commit(void);
const char* atp_get_version_branch(void);
int atp_is_dirty(void);
int atp_is_clean(void);
const char* atp_get_build_date(void);
const char* atp_get_build_time(void);
const char* atp_get_compiler(void);
const char* atp_get_arch(void);

#endif /* ATP_VERSION_H */
